### ISSUE TITLE
No diffusion.Model file

### ISSUE THREAD

**Issue by gagewrye** [cabralpinto/modular-diffusion#16]
The Model file is missing, making the repo unusable.

**Comment by cabralpinto** [comment]
Hi @gagewrye, thanks for the issue. This is by design. `Model` is a class declared inside `__init__.py`. Does this solve your problem?

**Comment by gagewrye** [comment]
Thanks for the quick reply! It wasn't initializing at first for some reason and I couldn't use the Model class. It's working now though.
